version: "3.7"

services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./data:/var/lib/postgresql/data
